version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "31337:31337"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - auth-service

  auth-service:
    build: ./auth-service
    volumes:
      - ./auth-service:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
